include:
  - project: jonohill/gitlab-templates
    file: docker.yml
    ref: 62a7636bf2b74ff39266a90528c4540d3276c1f6

variables:
  DOCKERHUB_REPO: jonoh/docker-buildx-qemu

dockerhub-push:
  stage: deploy
  image: "$CI_REGISTRY_IMAGE"
  script:
    - echo "$DOCKERHUB_PASSWORD" | base64 -d | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - export DOCKER_VERSION=$(docker --version | perl -pe 's/^.*\s(\d+\.\d+\.\d+.+),.*$/\1/')
    - export BUILDX_VERSION=$(docker buildx version | perl -pe 's/^.*v?(\d+\.\d+\.\d+).*$/$1/')
    - docker tag "$CI_REGISTRY_IMAGE" "$DOCKERHUB_REPO:latest"
    - docker tag "$CI_REGISTRY_IMAGE" "$DOCKERHUB_REPO:${DOCKER_VERSION}_${BUILDX_VERSION}"
    - docker push "$DOCKERHUB_REPO"
  only:
    - master
